version: "3"
services:
  db:
    container_name: postgresTest
    #image: postgres
    build:
      context: ./config
      dockerfile: db.Dockerfile
    #volumes:
      #- ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432


  metrobus:
    build: .
    ports:
      - 6969:6969

#volumes:
  #testDb:
